# Generated by Django 4.2.30 on 2026-05-04 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Dorji Wangchuk', max_length=100)),
                ('tagline', models.CharField(default="Code, stories, and ideas from Dorji's world.", help_text='Short line shown under your name on the homepage.', max_length=200)),
                ('bio', models.TextField(blank=True, help_text='A few sentences about yourself. Shown on the homepage and about page.')),
                ('profile_picture', models.ImageField(blank=True, help_text='Your photo — shown on the homepage hero section.', null=True, upload_to='profile/')),
                ('github_url', models.URLField(blank=True, default='https://github.com/dorjiwangchuk')),
                ('linkedin_url', models.URLField(blank=True, default='https://linkedin.com/in/dorjiwangchuk')),
                ('email', models.EmailField(blank=True, default='dorji@dorjivers.me', max_length=254)),
            ],
            options={
                'verbose_name': 'Site Profile',
                'verbose_name_plural': 'Site Profile',
            },
        ),
    ]
