# Generated by Django 4.2.30 on 2026-05-04 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('description', models.TextField()),
                ('short_description', models.CharField(blank=True, help_text='One-line summary shown on the project card. Auto-generated if blank.', max_length=300)),
                ('image', models.ImageField(blank=True, help_text='Main project screenshot or thumbnail.', null=True, upload_to='projects/')),
                ('technologies', models.CharField(help_text='Comma-separated list e.g. Django, PostgreSQL, Tailwind CSS', max_length=500)),
                ('github_link', models.URLField(blank=True)),
                ('live_demo_link', models.URLField(blank=True)),
                ('featured', models.BooleanField(default=False, help_text='Featured projects appear on the homepage.')),
                ('order', models.PositiveIntegerField(default=0, help_text='Lower numbers appear first.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-featured', 'order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('icon', models.ImageField(blank=True, help_text='Optional skill icon/logo image.', null=True, upload_to='skills/')),
                ('level', models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced'), ('expert', 'Expert')], default='intermediate', max_length=20)),
                ('category', models.CharField(choices=[('frontend', 'Frontend'), ('backend', 'Backend'), ('database', 'Database'), ('devops', 'DevOps'), ('tools', 'Tools'), ('other', 'Other')], default='other', max_length=20)),
                ('order', models.PositiveIntegerField(default=0, help_text='Lower numbers appear first.')),
            ],
            options={
                'ordering': ['order', 'name'],
            },
        ),
    ]
